[environment]
#被测系统环境地址
base_url = https://httpbin.org
sys_name = 本地Mock测试环境
#邮箱地址
smtp_server: smtp.qq.com
smtp_port: 465
email_user: "xxx@qq.com"
email_pwd: "请填写邮箱授权码"
receiver_email: "xxx@qq.com"

[request]
#统一请求超时时间（秒）
timeout = 10

[assert]
#响应时间上限，超过则断言失败
sla_ms = 3000

[report]
#allure原始结果输出目录
allure_dir = report/allure-result
